### ISSUE TITLE
GPT partition GUID unspecified

### ISSUE THREAD

**Issue by erkinalp** [danrl/lanyfs-utils#2]
What is the type GUID for LanyardFS in a GPT?

**Comment by danrl** [comment]
As far as I know the GUID in GPT describes the partition type, not the type of the file system. So there is no LanyFS-specific GUID. You are free to use `0FC63DAF-8483-4772-8E79-3D69D8477DE4` which is a standard Linux data partition. The Kernel will detect the filesystem properly.

**Comment by danrl** [comment]
Feel free to re-open if you think the question was not answered well. Thanks!
